name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download
      run: Invoke-WebRequest https://expose.dev/expose-windows-amd64.zip -OutFile expose.zip
    - name: Extract
      run: Expand-Archive expose.zip
    - name: Auth
      run: .\expose\expose.exe auth $Env:EXPOSE_AUTH_TOKEN
      env:
        EXPOSE_AUTH_TOKEN: ${{ secrets.EXPOSE_AUTH_TOKEN }}
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
    - name: Enable RDP
      run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - name: Enable User Authentication
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Set Runner Admin Password
      run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
    - name: Create Tunnel
      run: .\expose\expose.exe tcp 3389
